# Change these first
owner: pixelysg # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: Peppermint
    url: https://peppermint.labs.pixely.io/
  - name: Peppermint API
    url: https://peppermint.api.labs.pixely.io/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.labs.pixely.io
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Peppermint 🎄
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: 🙂
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
